// Lee `.env` en la raíz del repo y genera
// `src/environments/environment.ts` y `environment.production.ts`.
//
// Ejecutado automáticamente por los hooks `predev`, `prebuild`, `pretest` de
// `package.json`. Falla con exit 1 si falta `.env` o si quedan variables sin
// reemplazar (placeholders `<...>`), para evitar bundles con secretos vacíos.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');
const envPath = resolve(repoRoot, '.env');

function parseEnv(raw) {
  const out = {};
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

let env;
try {
  env = parseEnv(readFileSync(envPath, 'utf8'));
} catch (err) {
  if (err.code === 'ENOENT') {
    console.error(`✘ No se encontró .env en ${envPath}.`);
    console.error(`  Copia .env.example a .env y rellena los valores.`);
    process.exit(1);
  }
  throw err;
}

const required = ['API_BASE_URL', 'API_KEY'];
const missing = required.filter((k) => !env[k] || env[k].startsWith('<'));
if (missing.length) {
  console.error(`✘ Faltan o quedan placeholders en .env: ${missing.join(', ')}`);
  process.exit(1);
}

const envDir = resolve(repoRoot, 'src/environments');
mkdirSync(envDir, { recursive: true });

const banner =
  '// GENERATED by scripts/build-env.mjs from .env — DO NOT EDIT MANUALLY.\n' +
  '// To change, edit .env and rerun `npm run dev` or `npm run build`.\n';

// Single-quoted string escape — alineado con el estilo Prettier del proyecto.
const sq = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const apiBaseUrl = sq(env.API_BASE_URL);
const apiKey = sq(env.API_KEY);

writeFileSync(
  resolve(envDir, 'environment.ts'),
  `${banner}\nexport const environment = {\n` +
    `  production: false,\n` +
    `  apiBaseUrl: ${apiBaseUrl},\n` +
    `  apiKey: ${apiKey},\n` +
    `};\n`,
);

writeFileSync(
  resolve(envDir, 'environment.production.ts'),
  `${banner}\nexport const environment = {\n` +
    `  production: true,\n` +
    `  apiBaseUrl: ${apiBaseUrl},\n` +
    `  apiKey: ${apiKey},\n` +
    `};\n`,
);

console.log(`✓ Generated src/environments/environment{,.production}.ts from .env`);
