// Lee `.env` en la raíz del repo y genera:
//   - `src/environments/environment.ts` y `environment.production.ts`
//   - sincroniza el `connect-src` del CSP en `src/index.html` con el origin
//     derivado de `API_BASE_URL`, para que cambiar `.env` no requiera
//     editar el HTML a mano (el browser bloquearía las requests si el CSP
//     apunta a un origin distinto del que usa el código TS).
//
// Ejecutado automáticamente por los hooks `predev`, `prebuild`, `pretest` de
// `package.json`. Falla con exit 1 si falta `.env` o si quedan variables sin
// reemplazar (placeholders `<...>`), para evitar bundles con secretos vacíos.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');
const envPath = resolve(repoRoot, '.env');

function parseEnv(raw) {
  const out = {};
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

let env;
try {
  env = parseEnv(readFileSync(envPath, 'utf8'));
} catch (err) {
  if (err.code === 'ENOENT') {
    console.error(`✘ No se encontró .env en ${envPath}.`);
    console.error(`  Copia .env.example a .env y rellena los valores.`);
    process.exit(1);
  }
  throw err;
}

const required = ['API_BASE_URL', 'TENANT_SLUG', 'APP_VERSION'];
const missing = required.filter((k) => !env[k] || env[k].startsWith('<'));
if (missing.length) {
  console.error(`✘ Faltan o quedan placeholders en .env: ${missing.join(', ')}`);
  process.exit(1);
}

const envDir = resolve(repoRoot, 'src/environments');
mkdirSync(envDir, { recursive: true });

const banner =
  '// GENERATED by scripts/build-env.mjs from .env — DO NOT EDIT MANUALLY.\n' +
  '// To change, edit .env and rerun `npm run dev` or `npm run build`.\n';

// Single-quoted string escape — alineado con el estilo Prettier del proyecto.
const sq = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const apiBaseUrl = sq(env.API_BASE_URL);
const tenantSlug = sq(env.TENANT_SLUG);
const appVersion = sq(env.APP_VERSION);

writeFileSync(
  resolve(envDir, 'environment.ts'),
  `${banner}\nexport const environment = {\n` +
    `  production: false,\n` +
    `  apiBaseUrl: ${apiBaseUrl},\n` +
    `  tenantSlug: ${tenantSlug},\n` +
    `  appVersion: ${appVersion},\n` +
    `};\n`,
);

writeFileSync(
  resolve(envDir, 'environment.production.ts'),
  `${banner}\nexport const environment = {\n` +
    `  production: true,\n` +
    `  apiBaseUrl: ${apiBaseUrl},\n` +
    `  tenantSlug: ${tenantSlug},\n` +
    `  appVersion: ${appVersion},\n` +
    `};\n`,
);

console.log(`✓ Generated src/environments/environment{,.production}.ts from .env`);

// Nota: la inyección de `appData.version` en `ngsw.json` se hace en
// `scripts/inject-ngsw-appdata.mjs`, ejecutado por el hook `postbuild` de
// package.json. NO se hace acá porque `ng build` regenera `ngsw.json` desde
// cero y descartaría la mutación.

// --- Sincronizar CSP del index.html con API_BASE_URL ---
//
// El meta CSP del index.html restringe `connect-src` para mitigar XSS
// roba-bearer. Cuando .env cambia el host de la API, este script reescribe
// el origin que aparece en `connect-src` para que el browser permita las
// requests. Es idempotente: si el origin ya está sincronizado, no toca el
// archivo (evita ruido en git status).

let apiOrigin;
try {
  apiOrigin = new URL(env.API_BASE_URL).origin;
} catch {
  console.error(`✘ API_BASE_URL inválida en .env: "${env.API_BASE_URL}".`);
  process.exit(1);
}

const indexPath = resolve(repoRoot, 'src/index.html');
const indexBefore = readFileSync(indexPath, 'utf8');

// Regex sobre el atributo content del meta CSP. Capta cualquier sub-string
// dentro de `connect-src 'self' <ORIGIN>;` o `connect-src 'self' <ORIGIN>"`
// (último item de la lista de directivas) y lo reemplaza por apiOrigin.
const cspConnectSrcRe = /(connect-src\s+'self'\s+)([^;"']+)/;
const match = indexBefore.match(cspConnectSrcRe);
if (!match) {
  console.error(
    "✘ No se encontró `connect-src 'self' <origin>` en src/index.html. " +
      'Revisar el meta Content-Security-Policy.',
  );
  process.exit(1);
}

const currentOrigin = match[2].trim();
if (currentOrigin === apiOrigin) {
  console.log(`✓ CSP connect-src ya apunta a ${apiOrigin} (sin cambios)`);
} else {
  const indexAfter = indexBefore.replace(cspConnectSrcRe, `$1${apiOrigin}`);
  writeFileSync(indexPath, indexAfter);
  console.log(`✓ CSP connect-src actualizado: ${currentOrigin} → ${apiOrigin}`);
}
